name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [14.15.1]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node_version: ${{ matrix.node_version }}

      - name: Web CI
        run: |
          npm install # or yarn install
          npm run lint:fix
          npm run test
          npm run build
